<a href="https://colab.research.google.com/github/SIUSIUSIUSIU/Colab_-practice/blob/main/20220825_%EC%9D%B8%EA%B3%B5%EC%8B%A0%EA%B2%BD%EB%A7%9D(%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C_1_x).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
!pip install tensorflow==1.15.2

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [37]:
import tensorflow as tf
import numpy as np

In [38]:
tf.enable_eager_execution()
tf.__version__

'1.15.2'

In [39]:
X= np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
], dtype="float32")

y= np.array([
    [0],
    [0],
    [0],
    [1]
], dtype="float32")

In [40]:
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [41]:
y

array([[0.],
       [0.],
       [0.],
       [1.]], dtype=float32)

In [42]:
w= tf.Variable([
    [1],
    [2]
], dtype="float32")
b= tf.Variable([3], dtype="float32")

In [43]:
w

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[1.],
       [2.]], dtype=float32)>

In [44]:
b

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([3.], dtype=float32)>

In [45]:
tf.matmul(X,w) # X * w

<tf.Tensor: id=30443, shape=(4, 1), dtype=float32, numpy=
array([[0.],
       [2.],
       [1.],
       [3.]], dtype=float32)>

In [46]:
tf.matmul(X,w)+b # X * w + b

<tf.Tensor: id=30448, shape=(4, 1), dtype=float32, numpy=
array([[3.],
       [5.],
       [4.],
       [6.]], dtype=float32)>

In [47]:
tf.sigmoid(tf.matmul(X,w)+b)

<tf.Tensor: id=30454, shape=(4, 1), dtype=float32, numpy=
array([[0.95257413],
       [0.9933072 ],
       [0.98201376],
       [0.9975274 ]], dtype=float32)>

In [48]:
optimizer = tf.train.AdamOptimizer(0.1) # w, b 값을 자동으로 수정해줌

In [49]:
with tf.GradientTape() as tape:
  hypothesis = tf.sigmoid(tf.matmul(X,w)+b)
  print("hypothesis=", hypothesis)
  cost = -tf.reduce_mean(y * tf.log(hypothesis) + (1 - y) * tf.log(1 - hypothesis))
  print("cost=", cost)
  # reduce_mean : sum과 같은 역할

hypothesis= tf.Tensor(
[[0.95257413]
 [0.9933072 ]
 [0.98201376]
 [0.9975274 ]], shape=(4, 1), dtype=float32)
cost= tf.Tensor(3.0189826, shape=(), dtype=float32)


In [50]:
with tf.GradientTape() as tape:
 
  hypothesis = tf.sigmoid(tf.matmul(X,w)+b)
  print("hypothesis=", hypothesis)
  
  cost = -tf.reduce_mean(y * tf.log(hypothesis) + (1 - y) * tf.log(1 - hypothesis))
  print("cost=", cost)
  # reduce_mean : sum과 같은 역할
  
  grads=tape.gradient(cost,[w,b])
  print("기울기 grads=", grads)

  print("w 업데이트 전=", w)
  print("b 업데이트 전=", b)

  print("zip(grads,[w,b])=",list(zip(grads,[w,b])) )
  optimizer.apply_gradients(grads_and_vars=zip(grads,[w,b]))
  print("w 업데이트 후=", w)
  print("b 업데이트 후=", b)

hypothesis= tf.Tensor(
[[0.95257413]
 [0.9933072 ]
 [0.98201376]
 [0.9975274 ]], shape=(4, 1), dtype=float32)
cost= tf.Tensor(3.0189826, shape=(), dtype=float32)
기울기 grads= [<tf.Tensor: id=30523, shape=(2, 1), dtype=float32, numpy=
array([[0.2448853 ],
       [0.24770865]], dtype=float32)>, <tf.Tensor: id=30522, shape=(1,), dtype=float32, numpy=array([0.7313556], dtype=float32)>]
w 업데이트 전= <tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[1.],
       [2.]], dtype=float32)>
b 업데이트 전= <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([3.], dtype=float32)>
zip(grads,[w,b])= [(<tf.Tensor: id=30523, shape=(2, 1), dtype=float32, numpy=
array([[0.2448853 ],
       [0.24770865]], dtype=float32)>, <tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[1.],
       [2.]], dtype=float32)>), (<tf.Tensor: id=30522, shape=(1,), dtype=float32, numpy=array([0.7313556], dtype=float32)>, <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([3.], d

In [51]:
list(zip(["w1기울기","w2기울기"],["w1값","w2값"]))

[('w1기울기', 'w1값'), ('w2기울기', 'w2값')]

In [53]:
for i in range(200):
  print("i=",i)  
  with tf.GradientTape() as tape:
  
    hypothesis = tf.sigmoid(tf.matmul(X,w)+b)
    print("hypothesis=", hypothesis)
    
    cost = -tf.reduce_mean(y * tf.log(hypothesis) + (1 - y) * tf.log(1 - hypothesis))
    print("cost=", cost)
    # reduce_mean : sum과 같은 역할
    
    grads=tape.gradient(cost,[w,b])
    print("기울기 grads=", grads)

    print("w 업데이트 전=", w)
    print("b 업데이트 전=", b)

    print("zip(grads,[w,b])=",list(zip(grads,[w,b])) )
    optimizer.apply_gradients(grads_and_vars=zip(grads,[w,b]))
    print("w 업데이트 후=", w)
    print("b 업데이트 후=", b)
    print("="*100)

i= 0
hypothesis= tf.Tensor(
[[0.0110317 ]
 [0.17220083]
 [0.17128417]
 [0.7940031 ]], shape=(4, 1), dtype=float32)
cost= tf.Tensor(0.15465589, shape=(), dtype=float32)
기울기 grads= [<tf.Tensor: id=45648, shape=(2, 1), dtype=float32, numpy=
array([[-0.00867818],
       [-0.00844901]], dtype=float32)>, <tf.Tensor: id=45647, shape=(1,), dtype=float32, numpy=array([0.03712996], dtype=float32)>]
w 업데이트 전= <tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[2.9193358],
       [2.92578  ]], dtype=float32)>
b 업데이트 전= <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-4.495889], dtype=float32)>
zip(grads,[w,b])= [(<tf.Tensor: id=45648, shape=(2, 1), dtype=float32, numpy=
array([[-0.00867818],
       [-0.00844901]], dtype=float32)>, <tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[2.9193358],
       [2.92578  ]], dtype=float32)>), (<tf.Tensor: id=45647, shape=(1,), dtype=float32, numpy=array([0.03712996], dtype=float32)>, <tf.Variable 'Variable:0