<a href="https://colab.research.google.com/github/SIUSIUSIUSIU/Colab_-practice/blob/main/20220829_%EC%8B%AC%EC%B8%B5%EC%8B%A0%EA%B2%BD%EB%A7%9D_XOR_(%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C_1_x).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow==1.15.2

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import tensorflow as tf
import numpy as np
tf.enable_eager_execution()

In [ ]:
X= np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
], dtype="float32")

y= np.array([
    [0],
    [1],
    [1],
    [0]
], dtype="float32")

In [ ]:
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [ ]:
y

array([[0.],
       [1.],
       [1.],
       [0.]], dtype=float32)

In [ ]:
w0 = tf.Variable([
    [1,2],
    [3,4]
], dtype="float32")

In [ ]:
w0

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [ ]:
b0 = tf.Variable([[0,0]], dtype="float32")

In [ ]:
b0

<tf.Variable 'Variable:0' shape=(1, 2) dtype=float32, numpy=array([[0., 0.]], dtype=float32)>

In [ ]:
tf.matmul(X,w0)+b0

<tf.Tensor: id=23, shape=(4, 2), dtype=float32, numpy=
array([[0., 0.],
       [3., 4.],
       [1., 2.],
       [4., 6.]], dtype=float32)>

In [ ]:
hypothesis0 = tf.sigmoid(tf.matmul(X,w0)+b0)
hypothesis0

<tf.Tensor: id=29, shape=(4, 2), dtype=float32, numpy=
array([[0.5       , 0.5       ],
       [0.95257413, 0.98201376],
       [0.7310586 , 0.8807971 ],
       [0.98201376, 0.99752736]], dtype=float32)>

In [ ]:
w1 = tf.Variable([
    [5],
    [6]
], dtype="float32")

In [ ]:
w1

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[5.],
       [6.]], dtype=float32)>

In [ ]:
b1 = tf.Variable([[0]], dtype="float32")

In [ ]:
tf.matmul(hypothesis0,w1)+b1

<tf.Tensor: id=49, shape=(4, 1), dtype=float32, numpy=
array([[ 5.5     ],
       [10.654953],
       [ 8.940075],
       [10.895233]], dtype=float32)>

In [ ]:
hypothesis1 = tf.sigmoid(tf.matmul(hypothesis0,w1)+b1)
hypothesis1

<tf.Tensor: id=54, shape=(4, 1), dtype=float32, numpy=
array([[0.9959299],
       [0.9999764],
       [0.999869 ],
       [0.9999814]], dtype=float32)>

In [ ]:
optimizer = tf.train.AdamOptimizer(0.1)

In [ ]:
for step in range(5000):
  with tf.GradientTape() as tape:
    hypothesis0 = tf.sigmoid(tf.matmul(X,w0)+b0)
    hypothesis1 = tf.sigmoid(tf.matmul(hypothesis0,w1)+b1)
    cost = -tf.reduce_mean(y * tf.log(hypothesis1)+(1-y)* tf.log(1-hypothesis1))
    grads = tape.gradient(cost,[w0,w1,b0,b1])
    optimizer.apply_gradients(grads_and_vars=zip(grads,[w0,w1,b0,b1]))

    if step % 100 == 0:
      print("cost : {},w0 : {},w1 : {}".format(cost,w0,w1))
      print("=="*100)

cost : 4.0991926193237305,w0 : <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0.9000014, 1.9000086],
       [2.9000015, 3.9000084]], dtype=float32)>,w1 : <tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[4.9],
       [5.9]], dtype=float32)>
cost : 0.5574864149093628,w0 : <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-2.0565376, -4.4126096],
       [ 1.2810546,  3.060032 ]], dtype=float32)>,w1 : <tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[2.685531 ],
       [3.8502126]], dtype=float32)>
cost : 0.5103297233581543,w0 : <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-2.5863264, -6.2746296],
       [ 1.5904136,  4.880547 ]], dtype=float32)>,w1 : <tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[2.3543894],
       [4.411695 ]], dtype=float32)>
cost : 0.49529534578323364,w0 : <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-2.8877606, -7.377066