<a href="https://colab.research.google.com/github/SIUSIUSIUSIU/Colab_-practice/blob/main/20220902_2_4%EC%B0%A8%EC%9B%90_%ED%95%A9%EC%84%B1%EA%B3%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
w = np.array([
    [2,0],
    [0,0]
])

w

array([[2, 0],
       [0, 0]])

In [ ]:
from scipy.signal import correlate2d # 이차원배열 합성곱 연산
correlate2d(x, w, mode='valid')  # 벨리드 패딩

array([[ 2,  4],
       [ 8, 10]])

In [ ]:
correlate2d(x, w, mode='same')  # same 패딩

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
import tensorflow as tf

In [ ]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.array(x,dtype="float32")

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [ ]:
x = np.array(x,dtype="float32")

In [ ]:
x

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [ ]:
x = x.reshape(1,3,3,1) # 배열 ( 이미지 개수, 이미지 높이(줄), 이미지 너비(칸), 이미지 RGB(1은 흑백) )
x # 3 -> 4차원으로 변환

array([[[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]],

        [[7.],
         [8.],
         [9.]]]], dtype=float32)

In [ ]:
w

array([[2, 0],
       [0, 0]])

In [ ]:
w = np.array(w, dtype="float32" )
w

array([[2., 0.],
       [0., 0.]], dtype=float32)

In [ ]:
w = w.reshape(2,2,1,1) # 필터(가중치) 배열 ( 필터 너비(칸), 필터 높이(줄), 필터 RGB(1은 흑백), 필터 개수 )
w # 3 -> 4차원으로 변환

array([[[[2.]],

        [[0.]]],


       [[[0.]],

        [[0.]]]], dtype=float32)

In [ ]:
conv = tf.nn.conv2d(x,w,strides=1,padding='SAME') # 4차원 합성곱
conv

<tf.Tensor: shape=(1, 3, 3, 1), dtype=float32, numpy=
array([[[[ 2.],
         [ 4.],
         [ 6.]],

        [[ 8.],
         [10.],
         [12.]],

        [[14.],
         [16.],
         [18.]]]], dtype=float32)>

In [ ]:
# 2줄 2칸씩 그룹을 만들어 1칸씩 이동하며 최대값 리턴
tf.nn.max_pool2d(conv, ksize=2, strides=1, padding='VALID') # (객체, 줄칸 크기, 이동 크기, 연산법)

<tf.Tensor: shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[10.],
         [12.]],

        [[16.],
         [18.]]]], dtype=float32)>