<a href="https://colab.research.google.com/github/SIUSIUSIUSIU/Colab_-practice/blob/main/20220902_1%EC%B0%A8%EC%9B%90_%ED%95%A9%EC%84%B1%EA%B3%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x = np.array([2, 8, 3, 7, 1, 2, 0, 4, 5]) # 이미지

In [ ]:
x

array([2, 8, 3, 7, 1, 2, 0, 4, 5])

In [ ]:
w = np.array([3,5,1,2]) # 필터

In [ ]:
w

array([3, 5, 1, 2])

In [ ]:
from scipy.signal import correlate

In [ ]:
correlate(x, w, mode = 'valid') # 밸리드 패딩

array([63, 48, 49, 28, 21, 20])

In [ ]:
x

array([2, 8, 3, 7, 1, 2, 0, 4, 5])

In [ ]:
w = np.array([2,1,5,3])

In [ ]:
correlate(x, w, mode="same") # same 패딩

array([34, 51, 48, 57, 24, 25, 16, 39, 29])

In [ ]:
# 스트라이드 = 미끄러지는 배열의 간격