<a href="https://colab.research.google.com/github/SIUSIUSIUSIU/Colab_-practice/blob/main/20220831_%EB%8B%A4%EC%A4%91%EB%B6%84%EB%A5%98%EB%A5%BC_%EC%9D%B4%EC%9A%A9%ED%95%9C_%ED%8F%AC%EC%9C%A0%EB%A3%A8_%EC%A1%B0%EB%A5%98_%EB%B6%84%EB%A5%98(%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C_1_x)_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# 선형회귀 결과
z = np.array([
    [2.2, 1.39, 0.85]  # 입력이 자동차 이미지,
])                     # 입력이 비행기 이미지,
                       # 입력이 로켓 이미지

In [ ]:
!pip install tensorflow==1.15.2

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import tensorflow as tf

In [ ]:
tf.enable_eager_execution()
from tensorflow.nn import relu

In [ ]:
tf.nn.softmax(z)

<tf.Tensor: id=1, shape=(1, 3), dtype=float64, numpy=array([[0.5868206 , 0.26105188, 0.15212752]])>

In [ ]:
X = np.array([
    [0,0],
    [1,0],
    [1,1],
    [0,0],
    [0,1]
], dtype="float32")

X

array([[0., 0.],
       [1., 0.],
       [1., 1.],
       [0., 0.],
       [0., 1.]], dtype=float32)

In [ ]:
y = np.array([
    [1,0,0],
    [0,1,0],
    [0,0,1],
    [1,0,0],
    [0,0,1]
], dtype="float32")

y

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.]], dtype=float32)

In [ ]:
w0 = np.array([
    [1],
    [2]
], dtype="float32")

In [ ]:
X[2:3]

array([[1., 1.]], dtype=float32)

In [ ]:
np.dot(X[2:3],w0)

array([[3.]], dtype=float32)

In [ ]:
w0 = np.array([
    [1,3,5,7,9],
    [2,4,6,8,10]
], dtype="float32")

In [ ]:
w0.shape

(2, 5)

In [ ]:
np.dot(X[2:3], w0)

array([[ 3.,  7., 11., 15., 19.]], dtype=float32)

In [ ]:
w0 = np.array([
    [1,3,5,7,9,11,13,15,17,19],
    [2,4,6,8,10,12,14,16,18,20]
], dtype="float32")

In [ ]:
w0.shape

(2, 10)

In [ ]:
np.dot(X[2:3], w0)

array([[ 3.,  7., 11., 15., 19., 23., 27., 31., 35., 39.]], dtype=float32)

In [ ]:
np.dot(X, w0)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.],
       [ 3.,  7., 11., 15., 19., 23., 27., 31., 35., 39.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.]], dtype=float32)

In [ ]:
[1]*10

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [ ]:
b0 = np.array([1]*10, dtype="float32")

In [ ]:
np.dot(X, w0) + b0 # <- hypothesis0

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.],
       [ 4.,  8., 12., 16., 20., 24., 28., 32., 36., 40.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21.]], dtype=float32)

In [ ]:
w0

array([[ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.],
       [ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.]], dtype=float32)

In [ ]:
w0=tf.Variable(w0)

In [ ]:
b0

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [ ]:
b0=tf.Variable(b0)

In [ ]:
tf.matmul(X,w0)+b0

<tf.Tensor: id=21, shape=(5, 10), dtype=float32, numpy=
array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.],
       [ 4.,  8., 12., 16., 20., 24., 28., 32., 36., 40.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21.]], dtype=float32)>

In [ ]:
tf.sigmoid(tf.matmul(X,w0)+b0)

<tf.Tensor: id=27, shape=(5, 10), dtype=float32, numpy=
array([[0.7310586 , 0.7310586 , 0.7310586 , 0.7310586 , 0.7310586 ,
        0.7310586 , 0.7310586 , 0.7310586 , 0.7310586 , 0.7310586 ],
       [0.8807971 , 0.98201376, 0.99752736, 0.99966455, 0.9999546 ,
        0.9999939 , 0.9999991 , 0.99999994, 1.        , 1.        ],
       [0.98201376, 0.99966455, 0.9999939 , 0.99999994, 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.7310586 , 0.7310586 , 0.7310586 , 0.7310586 , 0.7310586 ,
        0.7310586 , 0.7310586 , 0.7310586 , 0.7310586 , 0.7310586 ],
       [0.95257413, 0.9933071 , 0.999089  , 0.9998766 , 0.9999833 ,
        0.99999774, 0.99999964, 1.        , 1.        , 1.        ]],
      dtype=float32)>

In [ ]:
hypothesis0 = tf.sigmoid(tf.matmul(X,w0)+b0)

In [ ]:
hypothesis0

<tf.Tensor: id=33, shape=(5, 10), dtype=float32, numpy=
array([[0.7310586 , 0.7310586 , 0.7310586 , 0.7310586 , 0.7310586 ,
        0.7310586 , 0.7310586 , 0.7310586 , 0.7310586 , 0.7310586 ],
       [0.8807971 , 0.98201376, 0.99752736, 0.99966455, 0.9999546 ,
        0.9999939 , 0.9999991 , 0.99999994, 1.        , 1.        ],
       [0.98201376, 0.99966455, 0.9999939 , 0.99999994, 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.7310586 , 0.7310586 , 0.7310586 , 0.7310586 , 0.7310586 ,
        0.7310586 , 0.7310586 , 0.7310586 , 0.7310586 , 0.7310586 ],
       [0.95257413, 0.9933071 , 0.999089  , 0.9998766 , 0.9999833 ,
        0.99999774, 0.99999964, 1.        , 1.        , 1.        ]],
      dtype=float32)>

In [ ]:
list(range(0,30))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29]

In [ ]:
np.array(list(range(0,30)), dtype="float32").reshape(10,3)

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.]], dtype=float32)

In [ ]:
w1 = np.array(list(range(0,30)), dtype="float32").reshape(10,3)

In [ ]:
w1

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.]], dtype=float32)

In [ ]:
b1 = np.array([1]*3,dtype="float32")

In [ ]:
w1 = tf.Variable(w1)

In [ ]:
b1 = tf.Variable(b1)

In [ ]:
hypothesis1 = tf.nn.softmax(tf.matmul(hypothesis0,w1)+b1)

In [ ]:
hypothesis1

<tf.Tensor: id=52, shape=(5, 3), dtype=float32, numpy=
array([[4.4649454e-07, 6.6797400e-04, 9.9933159e-01],
       [2.7273195e-09, 5.2222778e-05, 9.9994779e-01],
       [2.1380335e-09, 4.6237452e-05, 9.9995375e-01],
       [4.4649454e-07, 6.6797400e-04, 9.9933159e-01],
       [2.3014841e-09, 4.7972269e-05, 9.9995208e-01]], dtype=float32)>

In [ ]:
y

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.]], dtype=float32)

In [ ]:
tf.log(hypothesis1)

<tf.Tensor: id=53, shape=(5, 3), dtype=float32, numpy=
array([[-1.4621839e+01, -7.3112612e+00, -6.6863000e-04],
       [-1.9719946e+01, -9.8599920e+00, -5.2215033e-05],
       [-1.9963379e+01, -9.9817200e+00, -4.6254274e-05],
       [-1.4621839e+01, -7.3112612e+00, -6.6862995e-04],
       [-1.9889711e+01, -9.9448872e+00, -4.7923284e-05]], dtype=float32)>

In [ ]:
y * tf.log(hypothesis1)

<tf.Tensor: id=56, shape=(5, 3), dtype=float32, numpy=
array([[-1.4621839e+01, -0.0000000e+00, -0.0000000e+00],
       [-0.0000000e+00, -9.8599920e+00, -0.0000000e+00],
       [-0.0000000e+00, -0.0000000e+00, -4.6254274e-05],
       [-1.4621839e+01, -0.0000000e+00, -0.0000000e+00],
       [-0.0000000e+00, -0.0000000e+00, -4.7923284e-05]], dtype=float32)>

In [ ]:
cost = -tf.reduce_sum(y * tf.log(hypothesis1)) / len(hypothesis1) # len(hypothesis1) = 5 (줄 수)

In [ ]:
cost

<tf.Tensor: id=64, shape=(), dtype=float32, numpy=7.8207526>

In [ ]:
optimizer = tf.train.AdamOptimizer(0.01)

In [ ]:
for step in range(100):
    print("step=",step) 
    with tf.GradientTape() as tape:
        hypothesis0 = tf.sigmoid(tf.matmul(X,w0)+b0)
        hypothesis1 = tf.nn.softmax(tf.matmul(hypothesis0,w1)+b1)
        print("hypothesis1 =", hypothesis1)
        cost = -tf.reduce_sum(y * tf.log(hypothesis1)) / len(hypothesis1)
        print("cost =", cost)
        grads = tape.gradient(cost,[w0,w1,b0,b1])
        print("grads=", grads)
        print("w0 수정전 =",w0)
        print("w1 수정전 =",w1)
        print("b0 수정전 =",b0)
        print("b1 수정전 =",b1)

        optimizer.apply_gradients(grads_and_vars=zip(grads, [w0,w1,b0,b1]))
        print("w0 수정후 =",w0)
        print("w1 수정후 =",w1)
        print("b0 수정후 =",b0)
        print("b1 수정후 =",b1)  
        print("="*100)  

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
       0.69663805, 0.69663805, 0.69663805, 0.69663805, 0.69663805],
      dtype=float32)>
b1 수정전 = <tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1.3099983, 1.3057709, 0.6913422], dtype=float32)>
w0 수정후 = <tf.Variable 'Variable:0' shape=(2, 10) dtype=float32, numpy=
array([[ 0.6928555,  2.688254 ,  4.6875887,  6.687911 ,  8.690973 ,
        10.711625 , 12.806706 , 14.947133 , 16.995686 , 19.       ],
       [ 2.3346055,  4.2786818,  6.188195 ,  8.089459 , 10.023259 ,
        12.003716 , 14.000493 , 16.000065 , 18.       , 20.       ]],
      dtype=float32)>
w1 수정후 = <tf.Variable 'Variable:0' shape=(10, 3) dtype=float32, numpy=
array([[ 0.31737393,  1.3126894 ,  1.6843095 ],
       [ 3.3173718 ,  4.315603  ,  4.6833205 ],
       [ 6.317371  ,  7.3160515 ,  7.6831474 ],
       [ 9.317374  , 10.3161125 , 10.683125  ],
       [12.317374  , 13.316119  , 13.683124  ],
       [15.317374  , 16.316126  , 16.683125  ],
       [18.317375  , 19