<a href="https://colab.research.google.com/github/SIUSIUSIUSIU/Colab_-practice/blob/main/20220826_%EC%9D%B8%EA%B3%B5%EC%8B%A0%EA%B2%BD%EB%A7%9D%EC%9D%84_%EC%9D%B4%EC%9A%A9%ED%95%9C_%EC%9C%A0%EB%B0%A9%EC%95%94_%EB%B6%84%EB%A5%98_(tensorflow_1_x).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow==1.15.2

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import tensorflow as tf
tf.enable_eager_execution()
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np

In [3]:
datasets.load_breast_cancer()

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [4]:
cancer = datasets.load_breast_cancer()

In [5]:
cancer.data # 독립변수

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [6]:
X = cancer.data

In [7]:
X # 현재 데이터 타입 = 실수 (float64) -> 연산 오래걸림

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [8]:
X = np.array(X, dtype="float32") # X의 데이터 타입을 float32로 변환 
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]], dtype=float32)

In [9]:
# 양성 (pasitive) = 찾는 거 = 1
# 악성 (negative) = 관심 없음 = 0

y = cancer.target  # 종속변수
y                  # 악성이면 0 양성이면 1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [10]:
y = np.array(y, dtype="float32") # y의 데이터 타입을 float32로 변환 
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1.,
       1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1.,
       1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1.,
       0., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1.,
       1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1.,
       1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0.,
       1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1.,
       1., 1., 0., 1., 1.

In [11]:
y.shape # 몇 개의 데이터가 있어?

(569,)

In [12]:
y = y.reshape(1,-1) # 1줄 칸(생략)으로 변환
y

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        1., 1., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1.,
        0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1.,
        1., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0.,
        1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1.,
        1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0.,
        1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0., 1., 1.,
        1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
        1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 1.,
        1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 1.,
        1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0.,
        1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 

In [13]:
# y.reshape() = 1차원 배열을 2차원 배열로 변환
# y.reshape(1,-1) = 행 형태의 2차원 배열 ( -1은 생략이라는 뜻 )
# y.reshape(-1,1) = 열 형태의 2차원 배열 ( -1은 생략이라는 뜻 )
# 현재 X가 2차원 배열이기 때문에 y도 변환
# y = y.reshape(569,1) # 569줄 1칸으로 변환

y = y.reshape(-1,1) # 줄(생략) 1칸으로 변환
y

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],

In [14]:
# X, y 데이터 중 X_test, y_test에 20% (성능측정용) X_train, y_train에 80% 대입 (학습용)
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [15]:
X_train # 독립변수 80%

array([[1.805e+01, 1.615e+01, 1.202e+02, ..., 2.102e-01, 3.751e-01,
        1.108e-01],
       [2.059e+01, 2.124e+01, 1.378e+02, ..., 2.113e-01, 2.480e-01,
        8.999e-02],
       [1.486e+01, 2.321e+01, 1.004e+02, ..., 1.727e-01, 3.000e-01,
        8.701e-02],
       ...,
       [1.311e+01, 2.254e+01, 8.702e+01, ..., 1.126e-01, 4.128e-01,
        1.076e-01],
       [8.196e+00, 1.684e+01, 5.171e+01, ..., 2.564e-02, 3.105e-01,
        7.409e-02],
       [1.429e+01, 1.682e+01, 9.030e+01, ..., 3.333e-02, 2.458e-01,
        6.120e-02]], dtype=float32)

In [16]:
X_test # 독립변수 20%

array([[1.200e+01, 1.565e+01, 7.695e+01, ..., 7.632e-02, 3.379e-01,
        7.924e-02],
       [1.390e+01, 1.662e+01, 8.897e+01, ..., 6.222e-02, 2.679e-01,
        7.698e-02],
       [1.189e+01, 2.117e+01, 7.639e+01, ..., 8.263e-02, 3.075e-01,
        7.351e-02],
       ...,
       [2.309e+01, 1.983e+01, 1.521e+02, ..., 2.264e-01, 2.908e-01,
        7.277e-02],
       [1.199e+01, 2.489e+01, 7.761e+01, ..., 1.202e-01, 2.599e-01,
        8.251e-02],
       [1.221e+01, 1.802e+01, 7.831e+01, ..., 8.829e-02, 3.218e-01,
        7.470e-02]], dtype=float32)

In [17]:
y_train # 종속변수 80%

array([[0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],

In [18]:
y_test # 종속변수 20%

array([[1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],

In [19]:
# train (80%) = cost 최소인 w, b 찾기
# test (20%) = 찾은 w, b가 얼마나 정확한지 성능 측정

In [20]:
from sklearn.preprocessing import StandardScaler

In [21]:
scaler = StandardScaler()

In [22]:
# 각 칸의 평균 표준편차 구해서 scaler에 저장
scaler.fit(X_train)

StandardScaler()

In [23]:
# scaler.transform(X_train) = X_train - 평균 / 표준편차
X_train = scaler.transform(X_train)
X_train

array([[ 1.0521488 , -0.76732737,  1.0981112 , ...,  1.3655444 ,
         1.3677084 ,  1.3745478 ],
       [ 1.7749689 ,  0.4458784 ,  1.8231512 , ...,  1.3820333 ,
        -0.6654165 ,  0.2816899 ],
       [ 0.14435558,  0.91542935,  0.2824415 , ...,  0.8034256 ,
         0.16638947,  0.12519257],
       ...,
       [-0.35365018,  0.75573474, -0.2687538 , ..., -0.09746365,
         1.970768  ,  1.206497  ],
       [-1.7520502 , -0.6028652 , -1.723365  , ..., -1.4009799 ,
         0.33434996, -0.5533145 ],
       [-0.01785192, -0.60763234, -0.13363247, ..., -1.285708  ,
        -0.70060813, -1.2302456 ]], dtype=float32)

In [24]:
X_train.shape

(455, 30)

In [25]:
# w, b 의 초기값을 생성해주는 객체
# xavier 계산법 사용
initializer = tf.contrib.layers.xavier_initializer()

The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.



In [26]:
# 30줄 1칸으로 데이터 return
initializer([30,1])

<tf.Tensor: id=6, shape=(30, 1), dtype=float32, numpy=
array([[-0.43345347],
       [ 0.42171645],
       [-0.25969803],
       [ 0.1294114 ],
       [-0.17451042],
       [-0.07449836],
       [ 0.06820023],
       [ 0.30866003],
       [-0.43352574],
       [-0.00089335],
       [ 0.18190956],
       [ 0.08473426],
       [ 0.3615088 ],
       [-0.25787747],
       [ 0.10174084],
       [ 0.09956765],
       [ 0.12214011],
       [ 0.23172843],
       [ 0.2537626 ],
       [-0.2927528 ],
       [-0.1195229 ],
       [-0.09201366],
       [-0.2566858 ],
       [ 0.12395942],
       [-0.27976385],
       [-0.27925575],
       [ 0.31888074],
       [-0.07369637],
       [ 0.40010184],
       [ 0.20092273]], dtype=float32)>

In [27]:
w = tf.Variable(initializer([30,1]))
w

<tf.Variable 'Variable:0' shape=(30, 1) dtype=float32, numpy=
array([[-0.10613042],
       [ 0.12155104],
       [-0.2767338 ],
       [-0.2952571 ],
       [ 0.33238304],
       [-0.32953498],
       [ 0.43135995],
       [-0.28359747],
       [ 0.13373047],
       [ 0.03231782],
       [ 0.28614926],
       [-0.42155558],
       [-0.40810865],
       [-0.1849469 ],
       [-0.16282064],
       [ 0.33151507],
       [-0.03489181],
       [-0.27723107],
       [ 0.41285312],
       [-0.2888527 ],
       [ 0.27956605],
       [-0.36742866],
       [-0.34363243],
       [-0.3809313 ],
       [ 0.26632595],
       [ 0.26343173],
       [-0.19455242],
       [ 0.1426729 ],
       [-0.3251791 ],
       [-0.40531394]], dtype=float32)>

In [28]:
b = tf.Variable(initializer([1]))
b

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.0973786], dtype=float32)>

In [29]:
# X_train = 1줄 30칸  w = 30줄 1칸
tf.matmul(X_train[0:1],w)+b 

<tf.Tensor: id=42, shape=(1, 1), dtype=float32, numpy=array([[-0.13104284]], dtype=float32)>

In [30]:
X_train[0:3]

array([[ 1.0521488 , -0.76732737,  1.0981112 ,  0.93384737,  0.72542495,
         1.9733765 ,  0.92950577,  1.4388856 ,  1.295749  ,  0.5471887 ,
         2.0017805 , -1.1974164 ,  1.6253911 ,  1.9821641 ,  0.3313677 ,
         1.8095155 ,  0.49432462,  1.402281  ,  0.7073996 ,  1.1378096 ,
         1.2139014 , -1.1414804 ,  1.2195231 ,  1.2374473 ,  0.6485349 ,
         1.838395  ,  0.4513841 ,  1.3655444 ,  1.3677084 ,  1.3745478 ],
       [ 1.7749689 ,  0.4458784 ,  1.8231512 ,  1.8196335 ,  0.86835814,
         1.0538555 ,  1.550748  ,  1.543183  ,  0.16727965, -0.07297303,
         0.6222012 ,  0.02066163,  0.6111466 ,  0.70895356, -0.10203367,
         0.11946933,  0.29042336,  0.45599514, -1.1186076 , -0.04343778,
         1.5206487 ,  0.8094118 ,  1.6119876 ,  1.5027728 ,  0.5882174 ,
         0.5950862 ,  1.1100025 ,  1.3820333 , -0.6654165 ,  0.2816899 ],
       [ 0.14435558,  0.91542935,  0.2824415 , -0.01005066,  0.575345  ,
         1.6693119 ,  0.94552976,  0.94995934, -0

In [31]:
tf.matmul(X_train[0:3], w)

<tf.Tensor: id=45, shape=(3, 1), dtype=float32, numpy=
array([[-1.2284217 ],
       [-2.325938  ],
       [ 0.07161005]], dtype=float32)>

In [32]:
tf.matmul(X_train[0:3], w)+b

<tf.Tensor: id=50, shape=(3, 1), dtype=float32, numpy=
array([[-0.13104308],
       [-1.2285594 ],
       [ 1.1689887 ]], dtype=float32)>

In [33]:
tf.sigmoid(tf.matmul(X_train[0:3], w) + b )

<tf.Tensor: id=56, shape=(3, 1), dtype=float32, numpy=
array([[0.467286  ],
       [0.22643366],
       [0.76296216]], dtype=float32)>

In [34]:
y_train[0:3]

array([[0.],
       [0.],
       [0.]], dtype=float32)

In [35]:
tf.sigmoid(tf.matmul(X_train, w) + b )

<tf.Tensor: id=62, shape=(455, 1), dtype=float32, numpy=
array([[4.67286050e-01],
       [2.26433665e-01],
       [7.62962222e-01],
       [6.27253413e-01],
       [8.08990240e-01],
       [1.78669691e-01],
       [9.25937176e-01],
       [8.79171491e-01],
       [1.61062390e-01],
       [8.73916090e-01],
       [9.70881820e-01],
       [8.86972904e-01],
       [8.94893408e-01],
       [6.10227883e-01],
       [9.32487309e-01],
       [7.22866058e-01],
       [8.70343447e-01],
       [8.82459819e-01],
       [7.60298491e-01],
       [8.48106623e-01],
       [8.19181204e-01],
       [8.15631509e-01],
       [7.02298880e-01],
       [8.53644729e-01],
       [8.84785533e-01],
       [3.27946365e-01],
       [8.59140158e-01],
       [9.35043573e-01],
       [8.34183812e-01],
       [8.41681421e-01],
       [7.64233112e-01],
       [5.61087489e-01],
       [5.33678412e-01],
       [2.98722446e-01],
       [8.92902493e-01],
       [7.65037894e-01],
       [5.18450737e-01],
       [8.41460109

In [36]:
hypothesis = tf.sigmoid(tf.matmul(X_train, w) + b )

In [37]:
hypothesis

<tf.Tensor: id=68, shape=(455, 1), dtype=float32, numpy=
array([[4.67286050e-01],
       [2.26433665e-01],
       [7.62962222e-01],
       [6.27253413e-01],
       [8.08990240e-01],
       [1.78669691e-01],
       [9.25937176e-01],
       [8.79171491e-01],
       [1.61062390e-01],
       [8.73916090e-01],
       [9.70881820e-01],
       [8.86972904e-01],
       [8.94893408e-01],
       [6.10227883e-01],
       [9.32487309e-01],
       [7.22866058e-01],
       [8.70343447e-01],
       [8.82459819e-01],
       [7.60298491e-01],
       [8.48106623e-01],
       [8.19181204e-01],
       [8.15631509e-01],
       [7.02298880e-01],
       [8.53644729e-01],
       [8.84785533e-01],
       [3.27946365e-01],
       [8.59140158e-01],
       [9.35043573e-01],
       [8.34183812e-01],
       [8.41681421e-01],
       [7.64233112e-01],
       [5.61087489e-01],
       [5.33678412e-01],
       [2.98722446e-01],
       [8.92902493e-01],
       [7.65037894e-01],
       [5.18450737e-01],
       [8.41460109

In [38]:
print("hypothesis[0:3]=", hypothesis[0:3])

hypothesis[0:3]= tf.Tensor(
[[0.46728605]
 [0.22643366]
 [0.7629622 ]], shape=(3, 1), dtype=float32)


In [39]:
b

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.0973786], dtype=float32)>

In [44]:
hypothesis = tf.sigmoid(tf.matmul(X_train, w) + b )
print("hypothesis[0:3]=", hypothesis[0:3])
cost = -sum((y_train * tf.log(hypothesis)) + ((1-y_train) * tf.log(1-hypothesis))) /455
print("cost=", cost)

hypothesis[0:3]= tf.Tensor(
[[0.45993698]
 [0.22251254]
 [0.76051116]], shape=(3, 1), dtype=float32)
cost= tf.Tensor([0.41436288], shape=(1,), dtype=float32)


In [45]:
from tensorflow_core import OptimizerOptions
optimizer = tf.train.AdamOptimizer(0.001)

In [46]:
with tf.GradientTape() as tape:

    hypothesis = tf.sigmoid( tf.matmul(X_train , w) + b )
    print("hypothesis = ", hypothesis[0:3])

    cost = -tf.reduce_mean( (y_train*tf.log(hypothesis)\
            +(1-y_train)*tf.log(1-hypothesis)) ) 
    print("cost = ", cost)

    grads = tape.gradient(cost, [w,b])
    print("기울기 grads = ", grads)
    
    print("업데이트 전 w =", w)
    print("업데이트 전 b =", b)
    optimizer.apply_gradients(
        grads_and_vars = zip(grads, [w, b])
    )
    print("업데이트 후 w =", w)
    print("업데이트 후 b =", b)
    print("="*100)

hypothesis =  tf.Tensor(
[[0.45993698]
 [0.22251254]
 [0.76051116]], shape=(3, 1), dtype=float32)
cost =  tf.Tensor(0.41436282, shape=(), dtype=float32)
기울기 grads =  [<tf.Tensor: id=4851, shape=(30, 1), dtype=float32, numpy=
array([[ 0.13794416],
       [ 0.07156379],
       [ 0.14207473],
       [ 0.12251551],
       [ 0.14561114],
       [ 0.14843722],
       [ 0.15845762],
       [ 0.17768177],
       [ 0.12609856],
       [ 0.0156115 ],
       [ 0.08729659],
       [-0.06380873],
       [ 0.0815045 ],
       [ 0.07657419],
       [-0.00765031],
       [ 0.05329173],
       [ 0.03852517],
       [ 0.07914228],
       [ 0.00786508],
       [-0.02112103],
       [ 0.15698276],
       [ 0.09079725],
       [ 0.15864831],
       [ 0.13524792],
       [ 0.18209414],
       [ 0.16850157],
       [ 0.1810632 ],
       [ 0.20762901],
       [ 0.16494787],
       [ 0.10655741]], dtype=float32)>, <tf.Tensor: id=4850, shape=(1,), dtype=float32, numpy=array([0.10410048], dtype=float32)>]
업데이트 전

In [47]:
for step in range(100):
    print("step =", step)
    
    with tf.GradientTape() as tape:

        hypothesis = tf.sigmoid( tf.matmul(X_train , w) + b )
        print("hypothesis = ", hypothesis[0:3])

        cost = -tf.reduce_mean( (y_train*tf.log(hypothesis)\
                +(1-y_train)*tf.log(1-hypothesis)) ) 
        print("cost = ", cost)

        grads = tape.gradient(cost, [w,b])
        print("기울기 grads = ", grads)
        
        print("업데이트 전 w =", w)
        print("업데이트 전 b =", b)
        optimizer.apply_gradients(
            grads_and_vars = zip(grads, [w, b])
        )
        print("업데이트 후 w =", w)
        print("업데이트 후 b =", b)
        print("="*100)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
업데이트 후 b = <tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.0463303], dtype=float32)>
step = 51
hypothesis =  tf.Tensor(
[[0.18283814]
 [0.08491513]
 [0.6396416 ]], shape=(3, 1), dtype=float32)
cost =  tf.Tensor(0.2885887, shape=(), dtype=float32)
기울기 grads =  [<tf.Tensor: id=8801, shape=(30, 1), dtype=float32, numpy=
array([[ 0.08066712],
       [ 0.04838556],
       [ 0.08188611],
       [ 0.06915186],
       [ 0.08898644],
       [ 0.07396808],
       [ 0.08182815],
       [ 0.10066064],
       [ 0.06795295],
       [-0.00858538],
       [ 0.04439669],
       [-0.04626752],
       [ 0.03895387],
       [ 0.0379321 ],
       [-0.00621904],
       [ 0.00841425],
       [-0.00228706],
       [ 0.03198784],
       [-0.00287426],
       [-0.04143992],
       [ 0.09297425],
       [ 0.06292907],
       [ 0.09234535],
       [ 0.07659707],
       [ 0.12106104],
       [ 0.09354404],
       [ 0.10156948],
       [ 0.12515315],
       [ 0

In [48]:

input = np.array(
    [[1.2,0.3,0.5,0.4,0.8,
      0.7,0.1,0.9,0.7,50,
      20,80,90,70,55,
      78,45,89,45,77,
      51,454,78,88,96,
      11,22,33,44,55
      ]], dtype="float32")

In [49]:
scaler.transform(input)
input = scaler.transform(input)
tf.matmul(input,w)+b

<tf.Tensor: id=12426, shape=(1, 1), dtype=float32, numpy=array([[-8379.212]], dtype=float32)>

In [50]:
tf.sigmoid(  tf.matmul(input,w)+b )

<tf.Tensor: id=12432, shape=(1, 1), dtype=float32, numpy=array([[0.]], dtype=float32)>