<a href="https://colab.research.google.com/github/SIUSIUSIUSIU/Colab_-practice/blob/main/20220901_%EB%8B%A4%EC%A4%91%EB%B6%84%EB%A5%98%EB%A5%BC_%EC%9D%B4%EC%9A%A9%ED%95%9C_%EB%B6%93%EA%BD%83_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EB%A5%98_(%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C_1_x).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow==1.15.2

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 110.5 MB 38 kB/s 
     |████████████████████████████████| 3.8 MB 39.9 MB/s 
     |████████████████████████████████| 50 kB 7.6 MB/s 
     |████████████████████████████████| 503 kB 70.7 MB/s 
  Created wheel for gast: filename=gast-0.2.2-py3-none-any.whl size=7554 sha256=25485304428a27becb0bbaeb31e9f42d06226390b0acffc9760ad21f8afdc752
  Stored in directory: /root/.cache/pip/wheels/21/7f/02/420f32a803f7d0967b48dd823da3f558c5166991bfd204eef3
Successfully built gast
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.8.0
    Uninstalling tensorflow-estimator-2.8.0:
      Successfully uninstalled tensorflow-estimator-2.8.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.8.0
    Uninstalling tensorboard-2.8.0:
      Successfully uninstalled tensorboard-2.8.0
  Attempting un

In [ ]:
from sklearn import datasets
import tensorflow as tf
import numpy as np
from tensorflow.nn import relu
from sklearn.model_selection import train_test_split

In [ ]:
tf.enable_eager_execution()

In [ ]:
iris = datasets.load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [ ]:
X = iris.data
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
X = np.array(X, dtype="float32")
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
y = np.array(y, dtype="float32")

In [ ]:
X.shape

(150, 4)

In [ ]:
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
      dtype=float32)

In [ ]:
y.shape

(150,)

In [ ]:
y.reshape(-1,1)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [ ]:
y = y.reshape(-1,1)
y

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [ ]:
from sklearn.preprocessing import OneHotEncoder # one hot 인코딩 할 객체
enc=OneHotEncoder()
enc.fit(y) # y가 몇 종류인지
# fit 함수는 주어진 데이터셋에 대하여 최대,최소,평균,분산 등의 scaling에 필요한 정보를 파악

OneHotEncoder()

In [ ]:
enc.transform(y)

<150x3 sparse matrix of type '<class 'numpy.float64'>'
	with 150 stored elements in Compressed Sparse Row format>

In [ ]:
enc.transform(y).toarray()

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [ ]:
y = enc.transform(y).toarray()

In [ ]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [ ]:
X_train

array([[6.1, 3. , 4.9, 1.8],
       [6.3, 2.5, 5. , 1.9],
       [4.4, 3.2, 1.3, 0.2],
       [6.3, 3.4, 5.6, 2.4],
       [5.7, 2.5, 5. , 2. ],
       [6.3, 2.9, 5.6, 1.8],
       [5. , 3.6, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [5. , 2.3, 3.3, 1. ],
       [5.7, 2.8, 4.5, 1.3],
       [5.7, 2.8, 4.1, 1.3],
       [6. , 2.2, 5. , 1.5],
       [6.7, 3.3, 5.7, 2.1],
       [4.9, 3.1, 1.5, 0.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.8, 3.2, 5.9, 2.3],
       [5.5, 2.4, 3.7, 1. ],
       [5.1, 3.7, 1.5, 0.4],
       [7.2, 3.6, 6.1, 2.5],
       [4.9, 2.4, 3.3, 1. ],
       [5. , 3.5, 1.3, 0.3],
       [6.2, 2.2, 4.5, 1.5],
       [7.4, 2.8, 6.1, 1.9],
       [5.5, 2.5, 4. , 1.3],
       [5. , 3.2, 1.2, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [6.3, 2.3, 4.4, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.1, 2.8, 4. , 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [6.5, 3.2, 5.1, 2. ],
       [6.9, 3.1, 5.4, 2.1],
       [5.6, 3. , 4.1, 1.3],
       [5.7, 2

In [ ]:
X_test

array([[5.4, 3.4, 1.5, 0.4],
       [6.7, 3.3, 5.7, 2.5],
       [7.3, 2.9, 6.3, 1.8],
       [5.2, 3.5, 1.5, 0.2],
       [5.8, 2.6, 4. , 1.2],
       [5.1, 3.8, 1.5, 0.3],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.8, 2.7, 5.1, 1.9],
       [5.5, 4.2, 1.4, 0.2],
       [6.7, 3.1, 4.7, 1.5],
       [5.1, 3.5, 1.4, 0.2],
       [6.1, 2.6, 5.6, 1.4],
       [5.4, 3.9, 1.7, 0.4],
       [6.4, 2.7, 5.3, 1.9],
       [5.6, 2.5, 3.9, 1.1],
       [4.6, 3.6, 1. , 0.2],
       [6.4, 2.8, 5.6, 2.2],
       [6.2, 3.4, 5.4, 2.3],
       [7.7, 3.8, 6.7, 2.2],
       [5.4, 3.4, 1.7, 0.2],
       [5.2, 4.1, 1.5, 0.1],
       [5.1, 2.5, 3. , 1.1],
       [5.5, 2.6, 4.4, 1.2],
       [5.9, 3. , 4.2, 1.5],
       [5.8, 2.7, 3.9, 1.2],
       [5. , 3.4, 1.5, 0.2],
       [5.6, 2.8, 4.9, 2. ],
       [5.7, 2.9, 4.2, 1.3],
       [5. , 3.3, 1.4, 0.2]], dtype=float32)

In [ ]:
y_train

array([[0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0

In [ ]:
y_test

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [ ]:
y_train = np.array(y_train, dtype="float32")
y_train

array([[0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0

In [ ]:
y_test = np.array(y_test, dtype="float32")
y_test

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]], dtype=float32)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler()

In [ ]:
X_train = scaler.transform(X_train)
X_train

array([[ 0.26305667, -0.05626894,  0.6088542 ,  0.7520103 ],
       [ 0.49863026, -1.2620317 ,  0.66665673,  0.8855033 ],
       [-1.7393156 ,  0.4260363 , -1.4720398 , -1.383877  ],
       [ 0.49863026,  0.9083415 ,  1.0134723 ,  1.5529683 ],
       [-0.20808992, -1.2620317 ,  0.66665673,  1.0189962 ],
       [ 0.49863026, -0.29742128,  1.0134723 ,  0.7520103 ],
       [-1.0325961 ,  1.3906463 , -1.4142373 , -1.383877  ],
       [ 1.3231364 ,  0.4260363 ,  0.49324885,  0.2180385 ],
       [ 1.0875634 , -0.5385742 ,  0.5510517 ,  0.2180385 ],
       [-1.0325961 , -1.744337  , -0.31598762, -0.31593332],
       [-0.20808992, -0.5385742 ,  0.37764373,  0.08454549],
       [-0.20808992, -0.5385742 ,  0.14643322,  0.08454549],
       [ 0.14527017, -1.9854894 ,  0.66665673,  0.3515315 ],
       [ 0.9697763 ,  0.66718864,  1.0712749 ,  1.1524891 ],
       [-1.1503825 ,  0.1848834 , -1.3564346 , -1.51737   ],
       [ 0.9697763 ,  0.1848834 ,  1.0134723 ,  1.5529683 ],
       [ 1.0875634 ,  0.

In [ ]:
initializer = tf.contrib.layers.xavier_initializer()

In [ ]:
w0 = tf.Variable(initializer([4,16]))
w0

<tf.Variable 'Variable:0' shape=(4, 16) dtype=float32, numpy=
array([[ 0.5078783 ,  0.454064  ,  0.24016106, -0.17290965, -0.11725402,
        -0.42388448, -0.47931433,  0.1296773 , -0.4021699 ,  0.29282504,
         0.40553474, -0.20986935, -0.00537407, -0.22148535,  0.48551667,
        -0.01171041],
       [-0.07231256, -0.43032947, -0.51144207,  0.15514576,  0.26031834,
         0.4622923 ,  0.00290191, -0.38933593,  0.2863381 , -0.2902009 ,
         0.26190287,  0.50508094, -0.3804048 , -0.08677888, -0.37669194,
         0.5036303 ],
       [-0.35001925,  0.20961553,  0.12332487,  0.31258434,  0.46446836,
         0.25744802,  0.34291005, -0.18176332, -0.01745427, -0.12512738,
         0.24279577,  0.4255141 ,  0.42709982,  0.03250813,  0.30675507,
        -0.15127748],
       [ 0.098351  , -0.00971776, -0.23317984,  0.47122407, -0.12009808,
         0.42991567, -0.10574812,  0.10399747, -0.45002478,  0.5265099 ,
         0.29593873,  0.08736366, -0.07066414,  0.12108272, -0.370552

In [ ]:
b0 = tf.Variable(initializer([16]))
b0

<tf.Variable 'Variable:0' shape=(16,) dtype=float32, numpy=
array([ 0.00858149, -0.21534264,  0.12357107, -0.01057243,  0.11847606,
        0.41517177,  0.41274932, -0.13272643, -0.2683585 ,  0.3110949 ,
       -0.02122879,  0.30836365, -0.3658818 ,  0.17399135,  0.08780661,
       -0.29227653], dtype=float32)>

In [ ]:
tf.matmul(X_train, w0)+b0

<tf.Tensor: id=35, shape=(120, 16), dtype=float32, numpy=
array([[ 0.0071015 ,  0.04863355,  0.11525857, ...,  0.23145927,
         0.14483115, -0.25435892],
       [ 0.20683315,  0.6852933 ,  0.76451254, ...,  0.30196068,
         0.6816722 , -0.8444619 ],
       [-0.5264504 , -1.4835534 , -0.37088457, ...,  0.3068365 ,
        -0.85590184, -0.13175017],
       ...,
       [ 0.07926843, -1.2065694 , -0.42972597, ..., -0.04291247,
        -0.49936137,  0.21743241],
       [ 0.01248727,  0.13336483,  0.34884846, ...,  0.18397333,
         0.39807314, -0.472956  ],
       [-0.06780338, -0.46582016, -0.37262982, ...,  0.13399586,
        -0.24770993,  0.21048746]], dtype=float32)>

In [ ]:
hypothesis0 = tf.sigmoid(tf.matmul(X_train,w0)+b0) # 첫번째 회귀

In [ ]:
hypothesis0

<tf.Tensor: id=41, shape=(120, 16), dtype=float32, numpy=
array([[0.5017754 , 0.512156  , 0.5287828 , ..., 0.5576078 , 0.5361446 ,
        0.43675092],
       [0.55152476, 0.6649191 , 0.68233263, ..., 0.5749217 , 0.6641118 ,
        0.3005959 ],
       [0.37134516, 0.18489128, 0.4083273 , ..., 0.57611287, 0.2981963 ,
        0.46711004],
       ...,
       [0.51980674, 0.23030862, 0.39419177, ..., 0.48927352, 0.3776908 ,
        0.5541449 ],
       [0.5031218 , 0.5332919 , 0.5863383 , ..., 0.54586405, 0.59822464,
        0.38391685],
       [0.48305565, 0.38560605, 0.40790573, ..., 0.53344893, 0.43838724,
        0.5524284 ]], dtype=float32)>

In [ ]:
w1 = tf.Variable(initializer([16,3])) # hypothesis0가 16줄이기때문에 16칸, 선형회귀 3번할꺼라 3줄 
w1

<tf.Variable 'Variable:0' shape=(16, 3) dtype=float32, numpy=
array([[ 0.15057641, -0.00699306, -0.45440987],
       [-0.00386906, -0.06973374, -0.47604316],
       [-0.28312624, -0.02889109,  0.31009525],
       [-0.30495968,  0.17301917,  0.23033345],
       [-0.21362951,  0.2474603 ,  0.53505856],
       [-0.05387253, -0.21222433, -0.18731791],
       [ 0.02441514,  0.5430233 ,  0.13673204],
       [-0.02784431, -0.5513006 ,  0.32927364],
       [ 0.25878376,  0.4676444 ,  0.16643882],
       [-0.07994795, -0.25489163,  0.30943555],
       [ 0.39970756,  0.11925381, -0.11887199],
       [ 0.08712256, -0.1554581 ,  0.42747957],
       [ 0.56113464, -0.22273344, -0.10745907],
       [-0.53942037, -0.38043392,  0.12937212],
       [ 0.30216235,  0.23539448, -0.10459992],
       [-0.05055457,  0.50796205, -0.0678784 ]], dtype=float32)>

In [ ]:
b1 = tf.Variable(initializer([3]))
b1

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([ 0.0864253 , -0.21809363, -0.05682278], dtype=float32)>

In [ ]:
tf.matmul(hypothesis0,w1)+b1

<tf.Tensor: id=93, shape=(120, 3), dtype=float32, numpy=
array([[ 0.09434873, -0.11788511,  0.5882507 ],
       [ 0.12881535, -0.3373574 ,  0.49008018],
       [ 0.00383112,  0.22163868,  0.66916645],
       [ 0.05956125, -0.0262208 ,  0.64104134],
       [ 0.04976541, -0.30573857,  0.5964428 ],
       [ 0.13756418, -0.15053254,  0.5797044 ],
       [ 0.06069574,  0.326833  ,  0.6231246 ],
       [ 0.22052202, -0.06807721,  0.4433517 ],
       [ 0.2154251 , -0.20685256,  0.4326908 ],
       [ 0.04551783, -0.23070705,  0.59099364],
       [ 0.09721833, -0.10439634,  0.60913813],
       [ 0.08697641, -0.1188646 ,  0.5860685 ],
       [ 0.1417563 , -0.36498237,  0.5001608 ],
       [ 0.13594204, -0.06065762,  0.5641207 ],
       [ 0.06650198,  0.1681931 ,  0.6000379 ],
       [ 0.11476398, -0.18287802,  0.5341624 ],
       [ 0.13626122, -0.12841505,  0.5460796 ],
       [ 0.10130417, -0.22425777,  0.5401689 ],
       [ 0.05552399,  0.3329001 ,  0.62285423],
       [ 0.13615948, -0.0243649

In [ ]:
hypothesis1 = tf.nn.softmax(tf.matmul(hypothesis0,w1)+b1)

In [ ]:
hypothesis1

<tf.Tensor: id=98, shape=(120, 3), dtype=float32, numpy=
array([[0.29006746, 0.23459949, 0.47533298],
       [0.32652608, 0.2048621 , 0.46861178],
       [0.2387495 , 0.29684865, 0.4644018 ],
       [0.26979792, 0.24761896, 0.48258317],
       [0.29168773, 0.20442066, 0.50389165],
       [0.30250567, 0.22678518, 0.47070906],
       [0.24631488, 0.32141978, 0.4322653 ],
       [0.33345336, 0.24986078, 0.4166859 ],
       [0.34503862, 0.22619076, 0.4287706 ],
       [0.2870205 , 0.21774592, 0.49523357],
       [0.28686985, 0.23449025, 0.47863987],
       [0.28891817, 0.23516856, 0.47591326],
       [0.32965204, 0.19860126, 0.47174674],
       [0.29797557, 0.24479274, 0.45723167],
       [0.26233006, 0.29041028, 0.4472597 ],
       [0.30640885, 0.22752914, 0.46606204],
       [0.3054369 , 0.23440887, 0.46015418],
       [0.30552387, 0.22062534, 0.47385085],
       [0.24490504, 0.32319203, 0.4319029 ],
       [0.29925832, 0.25487745, 0.44586426],
       [0.27674308, 0.22301921, 0.50023764]

In [ ]:
y_train * -tf.log(hypothesis1)

<tf.Tensor: id=102, shape=(120, 3), dtype=float32, numpy=
array([[0.        , 0.        , 0.7437397 ],
       [0.        , 0.        , 0.75798064],
       [1.4323404 , 0.        , 0.        ],
       [0.        , 0.        , 0.728602  ],
       [0.        , 0.        , 0.68539405],
       [0.        , 0.        , 0.75351506],
       [1.4011445 , 0.        , 0.        ],
       [0.        , 1.3868514 , 0.        ],
       [0.        , 1.4863765 , 0.        ],
       [0.        , 1.5244265 , 0.        ],
       [0.        , 1.4503412 , 0.        ],
       [0.        , 1.4474528 , 0.        ],
       [0.        , 0.        , 0.751313  ],
       [0.        , 0.        , 0.78256506],
       [1.3381518 , 0.        , 0.        ],
       [0.        , 0.        , 0.76343656],
       [0.        , 0.        , 0.7761937 ],
       [0.        , 1.5112894 , 0.        ],
       [1.4068848 , 0.        , 0.        ],
       [0.        , 0.        , 0.80774075],
       [0.        , 1.5004973 , 0.        

In [ ]:
tf.reduce_sum(
    y_train * -tf.log(hypothesis1)
)

<tf.Tensor: id=108, shape=(), dtype=float32, numpy=143.98642>

In [ ]:
tf.reduce_sum(
    y_train * -tf.log(hypothesis1)
) / len(hypothesis1)

<tf.Tensor: id=116, shape=(), dtype=float32, numpy=1.1998868>

In [ ]:
cost = tf.reduce_sum(
    y_train * -tf.log(hypothesis1)
) / len(hypothesis1)

In [ ]:
cost

<tf.Tensor: id=124, shape=(), dtype=float32, numpy=1.1998868>

In [ ]:
hypothesis0 = tf.sigmoid(tf.matmul(X_train,w0)+b0) # 첫번째 회귀
hypothesis1 = tf.nn.softmax(tf.matmul(hypothesis0,w1)+b1) # 두번째 회귀
print("hypothesis1=",hypothesis1[0:3])
print("y_train=",y_train[0:3])
cost = -tf.reduce_sum(y_train * tf.log(hypothesis1)) / len(hypothesis1)
print("cost=",cost) 

hypothesis1= tf.Tensor(
[[0.29006746 0.23459949 0.47533298]
 [0.32652608 0.2048621  0.46861178]
 [0.2387495  0.29684865 0.4644018 ]], shape=(3, 3), dtype=float32)
y_train= [[0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]]
cost= tf.Tensor(1.1998868, shape=(), dtype=float32)


In [ ]:
with tf.GradientTape() as tape: 
  hypothesis0 = tf.sigmoid(tf.matmul(X_train,w0)+b0) # 첫번째 회귀
  hypothesis1 = tf.nn.softmax(tf.matmul(hypothesis0,w1)+b1) # 두번째 회귀
  print("hypothesis1=",hypothesis1[0:3])
  print("y_train=",y_train[0:3])
  cost = -tf.reduce_sum(y_train * tf.log(hypothesis1)) / len(hypothesis1)
  print("cost=",cost) 
  grads = tape.gradient(cost, [w0,w1,b0,b1])
  print("grads=",grads)

hypothesis1= tf.Tensor(
[[0.29006746 0.23459949 0.47533298]
 [0.32652608 0.2048621  0.46861178]
 [0.2387495  0.29684865 0.4644018 ]], shape=(3, 3), dtype=float32)
y_train= [[0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]]
cost= tf.Tensor(1.1998868, shape=(), dtype=float32)
grads= [<tf.Tensor: id=264, shape=(4, 16), dtype=float32, numpy=
array([[ 0.04640483,  0.02836651, -0.04606543, -0.04191063, -0.06232766,
         0.01183124, -0.01508997, -0.01869196,  0.00239269, -0.02104041,
         0.03141455, -0.01974734,  0.05129771, -0.05258163,  0.02802722,
        -0.00775856],
       [-0.01386703, -0.00098865,  0.01649422,  0.03078411,  0.03363011,
        -0.00993468,  0.02986361, -0.02716708,  0.0106333 , -0.00799329,
        -0.0201746 , -0.01062795, -0.03757853,  0.01475143, -0.00490517,
         0.02718892],
       [ 0.05291155,  0.03075805, -0.05278701, -0.05177546, -0.07428688,
         0.01484206, -0.02319044, -0.01289912, -0.00020882, -0.02036219,
         0.03944842, -0.01815538,  0.06282234,

In [ ]:
optimizer = tf.train.AdamOptimizer(0.1)

In [ ]:
with tf.GradientTape() as tape: 
  hypothesis0 = tf.sigmoid(tf.matmul(X_train,w0)+b0) # 첫번째 회귀
  hypothesis1 = tf.nn.softmax(tf.matmul(hypothesis0,w1)+b1) # 두번째 회귀
  print("hypothesis1=",hypothesis1[0:3])
  print("y_train=",y_train[0:3])
  cost = -tf.reduce_sum(y_train * tf.log(hypothesis1)) / len(hypothesis1)
  print("cost=",cost) 
  grads = tape.gradient(cost, [w0,w1,b0,b1])
  # print("grads=",grads)
  print("w0 업제이트 전=",w0)
  print("w1 업제이트 전=",w1)
  print("b0 업제이트 전=",b0)
  print("b1 업제이트 전=",b1)
  optimizer.apply_gradients(grads_and_vars=zip(grads,[w0,w1,b0,b1]))
  print("w0 업제이트 후=",w0)
  print("w1 업제이트 후=",w1)
  print("b0 업제이트 후=",b0)
  print("b1 업제이트 후=",b1)

hypothesis1= tf.Tensor(
[[0.20656748 0.42804053 0.36539206]
 [0.15851516 0.4377006  0.40378428]
 [0.4939044  0.39470318 0.11139238]], shape=(3, 3), dtype=float32)
y_train= [[0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]]
cost= tf.Tensor(0.79707843, shape=(), dtype=float32)
w0 업제이트 전= <tf.Variable 'Variable:0' shape=(4, 16) dtype=float32, numpy=
array([[ 0.30843288,  0.25396174,  0.43876085,  0.02380235,  0.08142728,
        -0.6217328 , -0.32405245,  0.32957503, -0.5887646 ,  0.49169463,
         0.21019295, -0.02693781, -0.2045882 , -0.02561528,  0.28595513,
         0.06352494],
       [ 0.10255232, -0.38674587, -0.711557  , -0.04473804,  0.06018742,
         0.6613649 , -0.19635189, -0.19743116,  0.08881021, -0.14905411,
         0.44980007,  0.70428234, -0.18219376, -0.28395358, -0.2758277 ,
         0.30407754],
       [-0.5491927 ,  0.00953289,  0.3223968 ,  0.5103412 ,  0.66370654,
         0.05897641,  0.5226485 ,  0.01590128,  0.009181  ,  0.07484095,
         0.04796795,  0.6044762 ,  0.

In [ ]:
for step in range(100):
  with tf.GradientTape() as tape: 
    hypothesis0 = tf.sigmoid(tf.matmul(X_train,w0)+b0) # 첫번째 회귀
    hypothesis1 = tf.nn.softmax(tf.matmul(hypothesis0,w1)+b1) # 두번째 회귀
    print("hypothesis1=",hypothesis1[0:3])
    print("y_train=",y_train[0:3])
    cost = -tf.reduce_sum(y_train * tf.log(hypothesis1)) / len(hypothesis1)
    print("cost=",cost) 
    grads = tape.gradient(cost, [w0,w1,b0,b1])
    # # print("grads=",grads)
    # print("w0 업제이트 전=",w0)
    # print("w1 업제이트 전=",w1)
    # print("b0 업제이트 전=",b0)
    # print("b1 업제이트 전=",b1)
    optimizer.apply_gradients(grads_and_vars=zip(grads,[w0,w1,b0,b1]))
    # print("w0 업제이트 후=",w0)
    # print("w1 업제이트 후=",w1)
    # print("b0 업제이트 후=",b0)
    # print("b1 업제이트 후=",b1)
    print("="*100)

hypothesis1= tf.Tensor(
[[0.1360106  0.24292566 0.6210637 ]
 [0.08374801 0.25190303 0.66434896]
 [0.64837086 0.25044158 0.10118755]], shape=(3, 3), dtype=float32)
y_train= [[0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]]
cost= tf.Tensor(0.6826696, shape=(), dtype=float32)
hypothesis1= tf.Tensor(
[[0.08216877 0.18857592 0.7292553 ]
 [0.04215515 0.20471041 0.7531344 ]
 [0.76904744 0.16595528 0.06499729]], shape=(3, 3), dtype=float32)
y_train= [[0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]]
cost= tf.Tensor(0.627077, shape=(), dtype=float32)
hypothesis1= tf.Tensor(
[[0.05525012 0.22605428 0.71869564]
 [0.02460099 0.26255417 0.7128448 ]
 [0.847915   0.12000209 0.03208284]], shape=(3, 3), dtype=float32)
y_train= [[0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]]
cost= tf.Tensor(0.52499694, shape=(), dtype=float32)
hypothesis1= tf.Tensor(
[[0.03706044 0.33344665 0.6294929 ]
 [0.01446271 0.40570736 0.57983   ]
 [0.89090884 0.0948585  0.01423254]], shape=(3, 3), dtype=float32)
y_train= [[0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]]
cost= tf

In [ ]:
w0

<tf.Variable 'Variable:0' shape=(4, 16) dtype=float32, numpy=
array([[ 0.05203991,  0.62857324,  1.5079353 ,  0.7233306 ,  0.57729614,
        -1.7695445 ,  1.5648903 , -0.44763902,  0.55220705,  0.02460759,
        -0.7122673 , -1.0027205 , -0.8545607 ,  0.5176975 ,  0.5444483 ,
         0.6482924 ],
       [ 0.48994502, -0.20555688, -1.7505027 , -1.4688649 , -1.7289878 ,
         2.3640559 , -0.9526189 , -0.14305422,  0.34406978, -0.59433556,
         1.736648  ,  0.50800884,  1.6249509 , -1.9998043 ,  0.19835357,
        -0.29983628],
       [-2.1300492 , -1.7142961 ,  1.6490569 ,  1.6526998 ,  1.7378184 ,
        -1.4544125 ,  1.7520106 ,  1.8820708 , -2.5248203 ,  1.5889182 ,
        -1.0489955 ,  2.221163  , -1.105702  ,  1.4328837 , -2.073106  ,
        -1.5476605 ],
       [-1.6860297 , -2.031307  ,  1.256229  ,  1.8104017 ,  1.200346  ,
        -1.2016504 , -0.01092312,  2.1338325 , -2.6685672 ,  2.1660013 ,
        -0.88664234,  2.3106186 , -1.6102941 ,  1.5465748 , -2.525088

In [ ]:
b0

<tf.Variable 'Variable:0' shape=(16,) dtype=float32, numpy=
array([ 2.2960105 ,  1.2852882 ,  1.9600428 ,  1.5182685 , -0.86732167,
       -1.1492608 ,  1.3845464 , -1.7354008 ,  2.814358  , -2.0570488 ,
        0.25908878, -0.97898936,  1.2317852 , -1.1492134 ,  2.2986462 ,
        0.3101369 ], dtype=float32)>

In [ ]:
w1

<tf.Variable 'Variable:0' shape=(16, 3) dtype=float32, numpy=
array([[ 1.8793833 ,  0.9695109 , -2.371162  ],
       [-0.1393241 ,  0.98651195, -1.4793203 ],
       [-2.6200778 ,  0.5312207 ,  0.7147975 ],
       [-2.5549138 ,  0.43307313,  0.9951972 ],
       [-2.3541818 , -0.0583196 ,  1.4880104 ],
       [ 2.2230158 , -0.40598693, -1.2080133 ],
       [-1.4014202 ,  0.74523497,  0.29398885],
       [-2.1119375 , -0.9238691 ,  1.3504591 ],
       [ 1.8632034 ,  1.3747805 , -2.1773515 ],
       [-1.8284757 , -0.47360623,  1.4183513 ],
       [ 1.3181627 ,  0.44007257, -0.61726075],
       [-1.4177742 , -0.74520135,  1.2272373 ],
       [ 1.7144446 ,  0.7191785 , -1.6590668 ],
       [-2.2453527 , -0.6451387 ,  0.982991  ],
       [ 1.1042097 ,  1.550205  , -1.7078558 ],
       [ 1.9926414 ,  0.6922028 , -0.7675398 ]], dtype=float32)>

In [ ]:
b1

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([ 1.2599283 , -0.07301163, -0.42650896], dtype=float32)>

In [ ]:
input_data = np.array(
    [
        [6.3,3.2,5.7,1.9],
        [5.7,2.6,4.01,1.2],
        [4.4,2.8,1.4,0.2]
    ],
dtype="float32")

In [ ]:
input_data

array([[6.3 , 3.2 , 5.7 , 1.9 ],
       [5.7 , 2.6 , 4.01, 1.2 ],
       [4.4 , 2.8 , 1.4 , 0.2 ]], dtype=float32)

In [ ]:
scaler.transform(input_data)

array([[ 0.49863026,  0.4260363 ,  1.0712749 ,  0.8855033 ],
       [-0.20808992, -1.0208795 ,  0.09441108, -0.04894734],
       [-1.7393156 , -0.5385742 , -1.4142373 , -1.383877  ]],
      dtype=float32)

In [ ]:
input_data = scaler.transform(input_data)
input_data

array([[ 0.49863026,  0.4260363 ,  1.0712749 ,  0.8855033 ],
       [-0.20808992, -1.0208795 ,  0.09441108, -0.04894734],
       [-1.7393156 , -0.5385742 , -1.4142373 , -1.383877  ]],
      dtype=float32)

In [ ]:
tf.sigmoid(tf.matmul(input_data,w0)+b0)

<tf.Tensor: id=9270, shape=(3, 16), dtype=float32, numpy=
array([[2.2371277e-01, 1.0677904e-01, 9.9219501e-01, 9.9030852e-01,
        8.3320522e-01, 2.5417387e-02, 9.7407317e-01, 8.6831903e-01,
        1.3805842e-01, 7.8954452e-01, 2.2010043e-01, 9.5941758e-01,
        2.4741107e-01, 7.6159549e-01, 1.4158219e-01, 6.5495044e-02],
       [8.4109968e-01, 7.8615725e-01, 9.7146046e-01, 9.4953555e-01,
        7.0743370e-01, 3.6511004e-02, 9.0001231e-01, 1.9419676e-01,
        9.0382308e-01, 1.9600815e-01, 1.9446695e-01, 2.3283970e-01,
        4.3171945e-01, 6.9934851e-01, 8.7110102e-01, 6.0311109e-01],
       [9.9931633e-01, 9.9608183e-01, 2.2083759e-02, 2.2065610e-02,
        6.3114762e-03, 9.8757005e-01, 3.6024034e-02, 1.5094876e-03,
        9.9986792e-01, 8.8912249e-04, 9.6349669e-01, 2.8791130e-03,
        9.9644256e-01, 5.8276355e-03, 9.9953413e-01, 9.7988492e-01]],
      dtype=float32)>

In [ ]:
hypothesis0 = tf.sigmoid(tf.matmul(input_data,w0)+b0)
hypothesis0

<tf.Tensor: id=9276, shape=(3, 16), dtype=float32, numpy=
array([[2.2371277e-01, 1.0677904e-01, 9.9219501e-01, 9.9030852e-01,
        8.3320522e-01, 2.5417387e-02, 9.7407317e-01, 8.6831903e-01,
        1.3805842e-01, 7.8954452e-01, 2.2010043e-01, 9.5941758e-01,
        2.4741107e-01, 7.6159549e-01, 1.4158219e-01, 6.5495044e-02],
       [8.4109968e-01, 7.8615725e-01, 9.7146046e-01, 9.4953555e-01,
        7.0743370e-01, 3.6511004e-02, 9.0001231e-01, 1.9419676e-01,
        9.0382308e-01, 1.9600815e-01, 1.9446695e-01, 2.3283970e-01,
        4.3171945e-01, 6.9934851e-01, 8.7110102e-01, 6.0311109e-01],
       [9.9931633e-01, 9.9608183e-01, 2.2083759e-02, 2.2065610e-02,
        6.3114762e-03, 9.8757005e-01, 3.6024034e-02, 1.5094876e-03,
        9.9986792e-01, 8.8912249e-04, 9.6349669e-01, 2.8791130e-03,
        9.9644256e-01, 5.8276355e-03, 9.9953413e-01, 9.7988492e-01]],
      dtype=float32)>

In [ ]:
hypothesis1 = tf.nn.softmax(tf.matmul(hypothesis0,w1)+b1)


In [ ]:
hypothesis1

<tf.Tensor: id=9281, shape=(3, 3), dtype=float32, numpy=
array([[4.1990198e-08, 7.1339412e-03, 9.9286604e-01],
       [2.0753653e-04, 9.9971634e-01, 7.6174743e-05],
       [9.9868172e-01, 1.3182937e-03, 1.1735587e-11]], dtype=float32)>

In [ ]:
tf.argmax(hypothesis1) # 칸 기준 제일 큰 값이 어느 줄에 있나

<tf.Tensor: id=9283, shape=(3,), dtype=int64, numpy=array([2, 1, 0])>